/*
 * Background.java
 *
 * Created on __DATE__, __TIME__
 */

package UI;

import java.awt.BorderLayout;
import java.awt.Container;

/**
 *
 * @author  __USER__
 */
public class Background extends javax.swing.JFrame {

	/** Creates new form Background */
	public Background() {
		initComponents();
		setSize(600, 500);
		setLocation(250, 200);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenu5 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenuItem9 = new javax.swing.JMenuItem();
		jMenuItem10 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jMenu1.setText("\u4ed3\u5e93\u7ba1\u7406");

		jMenuItem3.setText("\u5546\u54c1\u5f55\u5165");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuItem2.setText("\u8fdb\u8d27\u5355");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem4.setText("\u62a5\u635f\u5355");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem4);

		jMenuBar1.add(jMenu1);

		jMenu5.setText("\u4eba\u5458\u7ba1\u7406");

		jMenuItem1.setText("\u5458\u5de5\u7ba1\u7406");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu5.add(jMenuItem1);

		jMenuItem5.setText("\u4f9b\u8d27\u5546");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu5.add(jMenuItem5);

		jMenuBar1.add(jMenu5);

		jMenu2.setText("\u9500\u552e\u7ba1\u7406");

		jMenuItem7.setText("\u4ea4\u6613\u4fe1\u606f");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem7);

		jMenuItem8.setText("\u9000\u8d27");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem8);

		jMenuItem9.setText("\u5546\u54c1\u4fe1\u606f");
		jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem9ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem9);

		jMenuItem10.setText("\u5546\u54c1\u9500\u552e\u6392\u884c");
		jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem10ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem10);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new Ranking(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new GoodsInformation(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new Back(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new Information(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new Supplier(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new Loss(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new Receipt(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new GoodsInput(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Container container = getContentPane();
		container.removeAll();
		container.setLayout(new BorderLayout());
		add(new Employee(), BorderLayout.CENTER);
		((javax.swing.JComponent) container).updateUI();
	}

	/**
	 * @param args the command line arguments
	 */
	//	public static void main(String args[]) {
	//		java.awt.EventQueue.invokeLater(new Runnable() {
	//			public void run() {
	//				new Background().setVisible(true);
	//			}
	//		});
	//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem10;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	// End of variables declaration//GEN-END:variables

}