/*
 * member.java
 *
 * Created on __DATE__, __TIME__
 */

package UI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

import com.jdbc.Utils;

/**
 *
 * @author  __USER__
 */
public class member extends javax.swing.JFrame {

	/** Creates new form member */

	public member() {
		initComponents();
		setSize(600, 500);
		setLocation(250, 200);

		int row = 0;
		Statement st = null;
		st = Utils.getSt();
		try {
			//5、处理执行结果
			String sql2 = "select * from member";
			ResultSet rs = st.executeQuery(sql2);

			//5、处理执行结果
			while (rs.next()) {

				if (jTable1.getRowCount() - 1 < row) {
					DefaultTableModel tableModel = (DefaultTableModel) jTable1
							.getModel();
					tableModel.addRow(new Object[] { "" });
				}

				int Mid = rs.getInt(1);
				jTable1.setValueAt(Mid, row, 0);
				String Mname = rs.getString(2);
				jTable1.setValueAt(Mname, row, 1);
				String Mnumber = rs.getString(3);
				jTable1.setValueAt(Mnumber, row, 2);
				String Mphone = rs.getString(4);
				jTable1.setValueAt(Mphone, row, 3);
				int integral = rs.getInt(5);
				jTable1.setValueAt(integral, row, 4);
				String Mdate = rs.getString(6);
				jTable1.setValueAt(Mdate, row, 5);
				row++;
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jTextField2 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		getContentPane().setLayout(null);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel1.setText("\u4f1a\u5458\u7ba1\u7406\u8868");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(200, 10, 90, 24);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null } }, new String[] {
						"会员号", "用户名", "身份证", "联系方式", "开卡日期", "积分" }));
		jTable1.setRowHeight(20);
		jScrollPane1.setViewportView(jTable1);

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(30, 60, 452, 130);

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});
		getContentPane().add(jTextField2);
		jTextField2.setBounds(120, 270, 150, 23);

		jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel7.setText("\u8eab\u4efd\u8bc1\u53f7\uff1a");
		getContentPane().add(jLabel7);
		jLabel7.setBounds(30, 270, 70, 19);

		jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel8.setText("\u5f00\u5361\u65e5\u671f\uff1a");
		getContentPane().add(jLabel8);
		jLabel8.setBounds(310, 270, 70, 19);

		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});
		getContentPane().add(jTextField3);
		jTextField3.setBounds(380, 270, 110, 23);

		jLabel9.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel9.setText("\u67e5\u8be2\uff08\u624b\u673a\u53f7\uff09\uff1a");
		getContentPane().add(jLabel9);
		jLabel9.setBounds(30, 310, 120, 19);

		jTextField4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});
		getContentPane().add(jTextField4);
		jTextField4.setBounds(160, 310, 120, 23);

		jLabel10.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel10.setText("\u7528\u6237\u540d\uff1a");
		getContentPane().add(jLabel10);
		jLabel10.setBounds(30, 220, 60, 19);

		jTextField5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField5ActionPerformed(evt);
			}
		});
		getContentPane().add(jTextField5);
		jTextField5.setBounds(380, 220, 110, 23);

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton1);
		jButton1.setBounds(310, 310, 70, 25);

		jButton2.setText("\u5f55\u5165\u4f1a\u5458");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton2);
		jButton2.setBounds(169, 380, 90, 20);

		jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel11.setText("\u624b\u673a\u53f7\uff1a");
		getContentPane().add(jLabel11);
		jLabel11.setBounds(320, 220, 60, 19);

		jTextField6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField6ActionPerformed(evt);
			}
		});
		getContentPane().add(jTextField6);
		jTextField6.setBounds(110, 220, 120, 23);

		jButton5.setText("\u66f4\u65b0");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton5);
		jButton5.setBounds(310, 380, 70, 25);

		jButton3.setText("\u9000\u51fa");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton3);
		jButton3.setBounds(430, 380, 90, 25);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// 退出
		new pos().setVisible(true);
		this.dispose();
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		//更新(在表格显示所有信息)
		Statement st = null;
		st = Utils.getSt();
		int row = 0;

		try {
			//5、处理执行结果
			String sql2 = "select * from member";
			ResultSet rs = st.executeQuery(sql2);

			//5、处理执行结果
			while (rs.next()) {

				if (jTable1.getRowCount() - 1 < row) {
					DefaultTableModel tableModel = (DefaultTableModel) jTable1
							.getModel();
					tableModel.addRow(new Object[] { "" });
				}

				String Mid = Integer.toString(rs.getInt(1));
				jTable1.setValueAt(Mid, row, 0);
				String Mname = rs.getString(2);
				jTable1.setValueAt(Mname, row, 1);
				String Mnumber = rs.getString(3);
				jTable1.setValueAt(Mnumber, row, 2);
				String Mphone = rs.getString(4);
				jTable1.setValueAt(Mphone, row, 3);
				String integral_temp = rs.getString(5);
				jTable1.setValueAt(integral_temp, row, 4);
				String date = rs.getString(6);
				jTable1.setValueAt(date, row, 5);
				row++;
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		//录入(只是录入数据库，没在表格显示)
		String mname = this.jTextField6.getText();
		String mphone = this.jTextField5.getText();
		String mnumber = this.jTextField2.getText();
		String mdate = this.jTextField3.getText();
		int integral = 0;

		Statement st = null;
		st = Utils.getSt();
		try {
			//4、执行
			String sql1 = "insert into member(Mname,Mphone,Mnumber,integral,date) values('"
					+ mname
					+ "','"
					+ mphone
					+ "','"
					+ mnumber
					+ "','"
					+ integral + "','" + mdate + "');";
			st.executeUpdate(sql1);
		} catch (SQLException e) {
			e.printStackTrace();
		}

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//查询
		String mphone_temp = this.jTextField4.getText();
		Statement st = null;
		int i = 0;

		st = Utils.getSt();
		DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

		while (i < jTable1.getRowCount()) {
			tableModel.removeRow(0);
		}

		try {
			//4、执行
			String sql = "select * from member where Mphone ='" + mphone_temp
					+ "';";
			ResultSet rs = st.executeQuery(sql);

			int row = 0;
			//5、处理执行结果
			while (rs.next()) {
				if (jTable1.getRowCount() - 1 < row) {
					tableModel.addRow(new Object[] { "" });
				}

				int Mid = rs.getInt(1);
				jTable1.setValueAt(Mid, row, 0);
				String Mname = rs.getString(2);
				jTable1.setValueAt(Mname, row, 1);
				String Mnumber = rs.getString(3);
				jTable1.setValueAt(Mnumber, row, 2);
				String Mphone = rs.getString(4);
				jTable1.setValueAt(Mphone, row, 3);
				String Mdate = rs.getString(5);
				jTable1.setValueAt(Mdate, row, 4);
				int integral = rs.getInt(6);
				jTable1.setValueAt(integral, row, 5);
				row++;
			}
		}

		catch (SQLException e) {
			e.printStackTrace();
		}
	}

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables

}